### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by JunoJunho** [bherd/mc2mabs#1]
Hi,
I just wondered that how do I reproduce your work?

I repeated what you wrote in README.md file and the introduction of your homepage, but I could not build the your work.

```
abs.h:28:45:
     fatal error: boost/random/mersenne_twister.hpp: No such file or directory
compilation terminated.
```

I got this messages.

I installed g++ and ghc as you wrote in the introduction. I tried to do in the ubuntu machine.

**Comment by JunoJunho** [comment]
I installed library that contains C++ boost library.

However, I got new message.

```
ModelChecker.lhs:33:10:
    Could not find module ‘Data.List.Utils’
    Perhaps you haven't installed the profiling libraries for package ‘MissingH-1.4.0.1@Missi_D8aqEpsjQjc89ioxoM9kjO’?
    Use -v to see a list of the files searched for.

ModelChecker.lhs:34:10:
    Could not find module ‘Control.Monad.Reader’
    Perhaps you haven't installed the profiling libraries for package ‘mtl-2.2.1@mtl_Aue4leSeVkpKLsfHIV51E8’?
    Use -v to see a list of the files searched for.

ModelChecker.lhs:35:10:
    Could not find module ‘Control.Monad.State’
    Perhaps you haven't installed the profiling libraries for package ‘mtl-2.2.1@mtl_Aue4leSeVkpKLsfHIV51E8’?
    Use -v to see a list of the files searched for.

ModelChecker.lhs:38:10:
    Could not find module ‘System.Random’
    Perhaps you haven't installed the profiling libraries for package ‘random-1.1@rando_9Kgekc9yEaLHLNUuw6paWL’?
    Use -v to see a list of the files searched for.
```

I already had installed Haskell package, but how to run in this situation?

**Comment by JunoJunho** [comment]
You did not answer this.

**Comment by bherd** [comment]
Hi Junho, 

first of all, I really have to apologise for the terribly delayed response. I'm drowning in work at the moment and your question completely slipped my mind -- I'm really sorry for that!

Regarding your question: it seems that you haven't installed the profiling libraries installed on your system. Each of the libraries comes with a separate profiling-enabled version that needs to be installed separately. In order to do that, you just need to install the respective package with the _prof suffix. For example, for the first issue, you need to do the following (assuming you're using a Debian-based Linux): 

`sudo apt-get install libghc-missingh-prof`

Try to install all the missing libraries in a similar way and and let me know if it worked.  

In general, it might be a good idea to switch to version 2 of MC2MABS which is a bit more user-friendly. Although I have to admit that I didn't have enough time to work on usability yet. I should definitely do that ... 

Sorry again for the delay in getting back to you!

Ben

**Comment by JunoJunho** [comment]
Thanks I will check it.
